# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 926ad010ef04c6f8ac87b4f812e9c0514f587a740c570dd53042783d35419e85da4774f567e231a8e0c6ca2baed7af4bcc0ce34e20e9ace3fabc69f5fd712806

test:
  secret_key_base: e141041b8c125ff66897cf5d4bc245003eca89e37c9256f868b7f03ddc0060821958148a2c0518d60e54db92850c2a23ae84a64007e8a4b34440ad75d0cc0ede

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
